#!/usr/bin/env node
/**
 * Generate one TS module per core R4 StructureDefinition under
 * `src/structure/core/sd/` plus an `index.generated.ts` that maps each type
 * name to a dynamic `import()` of its module. The resulting layout lets the
 * default spec fetcher resolve any core SD at runtime without a network call,
 * while keeping each SD in its own bundler chunk so consumers only pay for
 * the types they actually render.
 *
 * Source: `fhir_spec/r4b_definitions.json/profiles-resources.json` — a copy
 * of the published FHIR Bundle of resource StructureDefinitions. Drop this
 * file in place yourself (the workspace ignores it from git); pointing at
 * R4B is fine for R4 consumers because the resource canonical URLs match.
 *
 * Run: `pnpm --filter @fhir-place/react-fhir sync:sds`
 *
 * Output is gitignored. The package's `prepare` step re-runs this so a fresh
 * clone with the source bundle in place produces the modules during install.
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

interface ElementDefinition {
  id?: string;
  path?: string;
}
interface StructureDefinition {
  resourceType: "StructureDefinition";
  kind?: string;
  derivation?: string;
  type?: string;
  snapshot?: { element?: ElementDefinition[] };
}
interface BundleEntry {
  resource?: { resourceType?: string };
}
interface Bundle {
  entry?: BundleEntry[];
}

const HERE = dirname(fileURLToPath(import.meta.url));
const SOURCE_PATH = join(
  HERE,
  "..",
  "fhir_spec",
  "r4b_definitions.json",
  "profiles-resources.json",
);
const OUTPUT_DIR = join(HERE, "..", "src", "structure", "core", "sd");

function isCoreResourceSd(sd: StructureDefinition): boolean {
  return (
    sd.resourceType === "StructureDefinition" &&
    sd.kind === "resource" &&
    sd.derivation === "specialization" &&
    typeof sd.type === "string" &&
    sd.type.length > 0 &&
    Array.isArray(sd.snapshot?.element)
  );
}

/**
 * Per-type module body. `JSON.parse(<string-literal>)` parses faster than the
 * equivalent JS object literal both for tsc and at runtime in V8, and keeps
 * the source file token-light so editor tooling stays responsive.
 */
function renderTypeModule(sd: StructureDefinition): string {
  const json = JSON.stringify(sd);
  return (
    `// AUTO-GENERATED by scripts/sync-bundled-structuredefinitions.ts. Do not edit.\n` +
    `import type { StructureDefinition } from "fhir/r4";\n\n` +
    `export const sd = JSON.parse(${JSON.stringify(json)}) as StructureDefinition;\n`
  );
}

function renderIndexModule(types: string[]): string {
  const sorted = [...types].sort();
  const entries = sorted
    .map((t) => `  ${JSON.stringify(t)}: () => import(${JSON.stringify(`./${t}.generated.js`)}),`)
    .join("\n");
  return (
    `// AUTO-GENERATED by scripts/sync-bundled-structuredefinitions.ts. Do not edit.\n` +
    `import type { StructureDefinition } from "fhir/r4";\n\n` +
    `export type StructureDefinitionLoader = () => Promise<{ sd: StructureDefinition }>;\n\n` +
    `/** One lazy `+'`import()`'+` per core resource SD; bundlers split each into its own chunk. */\n` +
    `export const loaders: Record<string, StructureDefinitionLoader> = {\n` +
    entries +
    `\n};\n\n` +
    `/** Sorted list of every type with a bundled SD. Useful for diagnostics. */\n` +
    `export const bundledTypes: ReadonlyArray<string> = ${JSON.stringify(sorted)};\n`
  );
}

function clearOutputDir(): void {
  if (!existsSync(OUTPUT_DIR)) return;
  for (const f of readdirSync(OUTPUT_DIR)) {
    if (f.endsWith(".generated.ts")) rmSync(join(OUTPUT_DIR, f));
  }
}

function main(): void {
  if (!existsSync(SOURCE_PATH)) {
    // On a fresh clone / CI the FHIR spec bundle isn't checked in; the empty
    // `index.generated.ts` stub committed alongside this script is what `tsc`
    // resolves so the package still builds. Skip silently so `pnpm dev` (which
    // runs this through `predev`) doesn't fail there.
    console.warn(
      `[sync:sds] Skipping — source bundle not found at ${SOURCE_PATH}.\n` +
        `[sync:sds] Drop the FHIR R4(B) "profiles-resources.json" there to populate per-type SDs.`,
    );
    return;
  }
  mkdirSync(OUTPUT_DIR, { recursive: true });
  clearOutputDir();

  const bundle = JSON.parse(readFileSync(SOURCE_PATH, "utf8")) as Bundle;
  const types: string[] = [];
  for (const entry of bundle.entry ?? []) {
    const sd = entry.resource as StructureDefinition | undefined;
    if (!sd || !isCoreResourceSd(sd)) continue;
    const type = sd.type as string;
    writeFileSync(join(OUTPUT_DIR, `${type}.generated.ts`), renderTypeModule(sd));
    types.push(type);
  }
  writeFileSync(join(OUTPUT_DIR, "index.generated.ts"), renderIndexModule(types));
  console.log(`Wrote ${types.length} StructureDefinition modules to ${OUTPUT_DIR}`);
}

main();
