#!/usr/bin/env node
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

type ValueSetContains = { system?: string; code?: string; display?: string; contains?: ValueSetContains[] };
type ValueSet = {
  resourceType: 'ValueSet';
  url?: string;
  status?: string;
  expansion?: { identifier?: string; timestamp?: string; total?: number; contains?: ValueSetContains[] };
};
type Bundle = { entry?: Array<{ resource?: unknown }> };

const HERE = dirname(fileURLToPath(import.meta.url));
const CACHE_DIR = join(HERE, 'cache', 'r4-spec');
const ZIP_PATH = join(CACHE_DIR, 'definitions.json.zip');
const EXPANSIONS_PATH = join(CACHE_DIR, 'expansions.json');
const OUTPUT_PATH = join(HERE, '..', 'src', 'structure', 'core', 'valuesets.generated.ts');
const MAX_CODES = 200;

function ensureExpansionsJson(): void {
  mkdirSync(CACHE_DIR, { recursive: true });
  if (!existsSync(ZIP_PATH)) {
    console.log('Downloading R4 definitions.json.zip ...');
    fetchToFile('https://hl7.org/fhir/R4/definitions.json.zip', ZIP_PATH);
  }
  if (!existsSync(EXPANSIONS_PATH)) {
    console.log('Extracting expansions.json ...');
    execFileSync('unzip', ['-o', '-j', ZIP_PATH, 'expansions.json', '-d', CACHE_DIR], { stdio: 'inherit' });
  }
}

function fetchToFile(url: string, outPath: string): void {
  const res = execFileSync('curl', ['-fsSL', url], { encoding: 'buffer', maxBuffer: 50 * 1024 * 1024 });
  writeFileSync(outPath, res);
}

function flattenContains(nodes: ValueSetContains[] | undefined): ValueSetContains[] {
  if (!nodes) return [];
  const out: ValueSetContains[] = [];
  const stack = [...nodes];
  while (stack.length > 0) {
    const cur = stack.pop()!;
    if (cur.code) out.push({ system: cur.system, code: cur.code, display: cur.display });
    if (cur.contains) stack.push(...cur.contains);
  }
  return out.reverse();
}

function generate(): string {
  const bundle = JSON.parse(readFileSync(EXPANSIONS_PATH, 'utf8')) as Bundle;
  const valueSets = (bundle.entry ?? [])
    .map((e) => e.resource)
    .filter((r): r is ValueSet => !!r && (r as ValueSet).resourceType === 'ValueSet');

  const rows: Array<[string, ValueSet]> = [];
  for (const vs of valueSets) {
    const url = vs.url;
    const contains = flattenContains(vs.expansion?.contains);
    const total = vs.expansion?.total ?? contains.length;
    if (!url || contains.length === 0) continue;
    if (contains.length > MAX_CODES) continue;
    if (total > contains.length) continue;
    rows.push([url, {
      resourceType: 'ValueSet',
      url,
      status: vs.status ?? 'active',
      expansion: {
        identifier: 'generated-from-fhir-r4-expansions',
        timestamp: new Date().toISOString(),
        total: contains.length,
        contains: contains.map((c) => ({ system: c.system, code: c.code, display: c.display })),
      },
    }]);
  }

  rows.sort((a, b) => a[0].localeCompare(b[0]));

  return `import type { ValueSet } from "fhir/r4";\n\n// AUTO-GENERATED by scripts/sync-bundled-valuesets.ts.\n// Do not edit by hand.\n\nexport const generatedCoreValueSets: Map<string, ValueSet> = new Map(\n${JSON.stringify(rows, null, 2)} as [string, ValueSet][],\n);\n`;
}

ensureExpansionsJson();
writeFileSync(OUTPUT_PATH, generate());
console.log(`Wrote ${OUTPUT_PATH}`);
