/**
 * Reads `fhir_spec/r4b_definitions.json/valuesets.json` (which is the FHIR R4
 * "valuesets+codesystems" bundle distributed by HL7) and emits a flat
 * `(system, code) → { display, definition }` index for the small CodeSystems
 * we want to surface in the UI (status enums, criticalities, etc.).
 *
 * SNOMED, LOINC, RxNorm, ICD-10 etc. ship in this bundle as stub CodeSystems
 * with `content: not-present` (no `concept[]`) — they're filtered out here
 * since their definitions live on external terminology servers.
 *
 * Output: `src/structure/core/codesystems.generated.ts`. Committed as an
 * empty stub on a fresh checkout (mirrors how SDs work) and regenerated by
 * `pnpm --filter @fhir-place/react-fhir sync:csys`.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

interface CodeSystemConcept {
  code?: string;
  display?: string;
  definition?: string;
  concept?: CodeSystemConcept[];
}

interface CodeSystem {
  resourceType: "CodeSystem";
  url?: string;
  content?: string;
  concept?: CodeSystemConcept[];
}

interface Bundle {
  entry?: Array<{ resource?: { resourceType?: string } }>;
}

const HERE = dirname(fileURLToPath(import.meta.url));
const SOURCE_PATH = join(
  HERE,
  "..",
  "fhir_spec",
  "r4b_definitions.json",
  "valuesets.json",
);
const OUTPUT_PATH = join(
  HERE,
  "..",
  "src",
  "structure",
  "core",
  "codesystems.generated.ts",
);

/** Cap per-system concept count to keep the bundle reasonable. */
const MAX_CONCEPTS_PER_SYSTEM = 200;

interface Entry {
  system: string;
  code: string;
  display?: string;
  definition?: string;
}

/** Walk a CodeSystem's nested `concept` tree and yield every leaf+branch. */
function flattenConcepts(
  concepts: CodeSystemConcept[] | undefined,
  out: CodeSystemConcept[] = [],
): CodeSystemConcept[] {
  for (const c of concepts ?? []) {
    out.push(c);
    if (c.concept?.length) flattenConcepts(c.concept, out);
  }
  return out;
}

function main(): void {
  if (!existsSync(SOURCE_PATH)) {
    // On CI / fresh clones the FHIR spec bundle isn't committed; the
    // already-committed `codesystems.generated.ts` is what gets shipped.
    // Skip silently so `pnpm dev` (which calls this through `predev`) works.
    console.warn(
      `[sync:csys] Skipping — source bundle not found at ${SOURCE_PATH}.\n` +
        `[sync:csys] Drop the FHIR R4(B) "valuesets.json" there to refresh CodeSystem definitions.`,
    );
    return;
  }
  const bundle = JSON.parse(readFileSync(SOURCE_PATH, "utf8")) as Bundle;
  const entries: Entry[] = [];
  let systemsBundled = 0;
  let systemsSkippedEmpty = 0;
  let systemsSkippedOversize = 0;

  for (const e of bundle.entry ?? []) {
    const cs = e.resource as CodeSystem | undefined;
    if (!cs || cs.resourceType !== "CodeSystem" || !cs.url) continue;
    const concepts = flattenConcepts(cs.concept);
    if (concepts.length === 0) {
      systemsSkippedEmpty += 1;
      continue;
    }
    if (concepts.length > MAX_CONCEPTS_PER_SYSTEM) {
      systemsSkippedOversize += 1;
      continue;
    }
    let pushed = 0;
    for (const c of concepts) {
      if (!c.code) continue;
      if (!c.display && !c.definition) continue;
      entries.push({
        system: cs.url,
        code: c.code,
        display: c.display,
        definition: c.definition,
      });
      pushed += 1;
    }
    if (pushed > 0) systemsBundled += 1;
  }

  // Stable order: by system, then by code.
  entries.sort((a, b) =>
    a.system === b.system
      ? a.code.localeCompare(b.code)
      : a.system.localeCompare(b.system),
  );

  // Pack as { [system]: { [code]: { d?: display, x?: definition } } }.
  // Short keys keep the on-disk file small; JSON.stringify omits undefined,
  // which is critical here — tuples would have written `null` for missing
  // slots and broken the type.
  const packed: Record<
    string,
    Record<string, { d?: string; x?: string }>
  > = {};
  for (const e of entries) {
    let inner = packed[e.system];
    if (!inner) {
      inner = {};
      packed[e.system] = inner;
    }
    const value: { d?: string; x?: string } = {};
    if (e.display) value.d = e.display;
    if (e.definition) value.x = e.definition;
    inner[e.code] = value;
  }

  const ts =
    `// AUTO-GENERATED by scripts/sync-bundled-codesystems.ts. Do not edit.\n` +
    `// (system, code) → { d: display, x: definition } for every R4 CodeSystem\n` +
    `// with inline concepts up to ${MAX_CONCEPTS_PER_SYSTEM} per system. Used by\n` +
    `// renderers to surface human labels and tooltips for codes whose\n` +
    `// resource-side .display is missing (e.g. AllergyIntolerance.clinicalStatus).\n` +
    `\n` +
    `export interface CoreConceptInfo { d?: string; x?: string }\n` +
    `\n` +
    `export const generatedCoreConcepts: Record<string, Record<string, CoreConceptInfo>> = ${JSON.stringify(packed)};\n`;

  writeFileSync(OUTPUT_PATH, ts);
  console.log(
    `Wrote ${entries.length} concepts across ${systemsBundled} CodeSystems to ${OUTPUT_PATH}`,
  );
  console.log(
    `  Skipped empty (content: not-present etc.): ${systemsSkippedEmpty}`,
  );
  console.log(
    `  Skipped over ${MAX_CONCEPTS_PER_SYSTEM} concepts:               ${systemsSkippedOversize}`,
  );
}

main();
