#!/usr/bin/env node
/**
 * Generate one TS module per core R4 StructureDefinition under
 * `src/structure/core/sd/` plus an `index.generated.ts` that maps each type
 * name to a dynamic `import()` of its module. The resulting layout lets the
 * default spec fetcher resolve any core SD at runtime without a network call,
 * while keeping each SD in its own bundler chunk so consumers only pay for
 * the types they actually render.
 *
 * Source: `scripts/cache/r4-spec/profiles-resources.json` — extracted from
 * the published FHIR R4 `definitions.json.zip`. Auto-downloaded on first
 * run if not already cached; the zip is gitignored but profiles-resources.json
 * can be committed to avoid the download. This is the same shared cache that
 * `sync-bundled-valuesets.ts` populates, so the two scripts download once
 * and reuse the bundle.
 *
 * Run: `pnpm --filter @fhir-place/react-fhir sync:sds`
 *
 * The per-type modules are committed when present. The build does NOT run
 * this script automatically — the committed files are the source of truth,
 * and the empty-loaders stub (index.generated.ts) is the fallback.
 */
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

interface ElementDefinition {
  id?: string;
  path?: string;
}
interface StructureDefinition {
  resourceType: "StructureDefinition";
  kind?: string;
  derivation?: string;
  type?: string;
  snapshot?: { element?: ElementDefinition[] };
}
interface BundleEntry {
  resource?: { resourceType?: string };
}
interface Bundle {
  entry?: BundleEntry[];
}

const HERE = dirname(fileURLToPath(import.meta.url));
const CACHE_DIR = join(HERE, "cache", "r4-spec");
const ZIP_PATH = join(CACHE_DIR, "definitions.json.zip");
const SOURCE_PATH = join(CACHE_DIR, "profiles-resources.json");
const SOURCE_URL = "https://hl7.org/fhir/R4/definitions.json.zip";
const OUTPUT_DIR = join(HERE, "..", "src", "structure", "core", "sd");

function ensureSpecData(): void {
  if (existsSync(SOURCE_PATH)) return;
  mkdirSync(CACHE_DIR, { recursive: true });
  if (!existsSync(ZIP_PATH)) {
    console.log(`[sync:sds] Downloading ${SOURCE_URL} ...`);
    const buf = execFileSync("curl", ["-fsSL", SOURCE_URL], {
      encoding: "buffer",
      maxBuffer: 100 * 1024 * 1024,
    });
    writeFileSync(ZIP_PATH, buf);
  }
  console.log("[sync:sds] Extracting profiles-resources.json ...");
  execFileSync(
    "unzip",
    ["-o", "-j", ZIP_PATH, "profiles-resources.json", "-d", CACHE_DIR],
    { stdio: "inherit" },
  );
}

function isCoreResourceSd(sd: StructureDefinition): boolean {
  return (
    sd.resourceType === "StructureDefinition" &&
    sd.kind === "resource" &&
    sd.derivation === "specialization" &&
    typeof sd.type === "string" &&
    sd.type.length > 0 &&
    Array.isArray(sd.snapshot?.element)
  );
}

/**
 * Per-type module body. `JSON.parse(<string-literal>)` parses faster than the
 * equivalent JS object literal both for tsc and at runtime in V8, and keeps
 * the source file token-light so editor tooling stays responsive.
 */
function renderTypeModule(sd: StructureDefinition): string {
  const json = JSON.stringify(sd);
  return (
    `// AUTO-GENERATED by scripts/sync-bundled-structuredefinitions.ts. Do not edit.\n` +
    `import type { StructureDefinition } from "fhir/r4";\n\n` +
    `export const sd = JSON.parse(${JSON.stringify(json)}) as StructureDefinition;\n`
  );
}

function renderIndexModule(types: string[]): string {
  const sorted = [...types].sort();
  const entries = sorted
    .map((t) => `  ${JSON.stringify(t)}: () => import(${JSON.stringify(`./${t}.generated.js`)}),`)
    .join("\n");
  return (
    `// AUTO-GENERATED by scripts/sync-bundled-structuredefinitions.ts. Do not edit.\n` +
    `import type { StructureDefinition } from "fhir/r4";\n\n` +
    `export type StructureDefinitionLoader = () => Promise<{ sd: StructureDefinition }>;\n\n` +
    `/** One lazy `+'`import()`'+` per core resource SD; bundlers split each into its own chunk. */\n` +
    `export const loaders: Record<string, StructureDefinitionLoader> = {\n` +
    entries +
    `\n};\n\n` +
    `/** Sorted list of every type with a bundled SD. Useful for diagnostics. */\n` +
    `export const bundledTypes: ReadonlyArray<string> = ${JSON.stringify(sorted)};\n`
  );
}

function clearOutputDir(): void {
  if (!existsSync(OUTPUT_DIR)) return;
  for (const f of readdirSync(OUTPUT_DIR)) {
    if (f.endsWith(".generated.ts")) rmSync(join(OUTPUT_DIR, f));
  }
}

function main(): void {
  ensureSpecData();
  mkdirSync(OUTPUT_DIR, { recursive: true });
  clearOutputDir();

  const bundle = JSON.parse(readFileSync(SOURCE_PATH, "utf8")) as Bundle;
  const types: string[] = [];
  for (const entry of bundle.entry ?? []) {
    const sd = entry.resource as StructureDefinition | undefined;
    if (!sd || !isCoreResourceSd(sd)) continue;
    const type = sd.type as string;
    writeFileSync(join(OUTPUT_DIR, `${type}.generated.ts`), renderTypeModule(sd));
    types.push(type);
  }
  // A non-empty loaders map is the whole point of this script — the
  // bundled-fallback fetcher relies on it. If we generated zero modules
  // (corrupt download, unexpected bundle shape) fail loudly rather than
  // letting an empty stub ship to production.
  if (types.length === 0) {
    throw new Error(
      `[sync:sds] No core resource StructureDefinitions found in ${SOURCE_PATH}. ` +
        `Refusing to overwrite the index with an empty loaders map.`,
    );
  }
  writeFileSync(join(OUTPUT_DIR, "index.generated.ts"), renderIndexModule(types));
  console.log(`Wrote ${types.length} StructureDefinition modules to ${OUTPUT_DIR}`);
}

main();
