/* eslint-disable */
// @generated by packages/react-fhir/scripts/codegen-spike.ts
// DO NOT EDIT BY HAND. Re-run the script to regenerate.
//
// Source: cached US Core 7.0.0 IG (scripts/cache/us-core-7/).
// Status: __experimental__ spike output for issue #123. NOT exported from
// the package barrel (`src/structure/index.ts`). See
// `docs/spikes/profile-codegen.md` for caveats and known limitations.

import type { Observation, Patient, Period } from "fhir/r4";

// ===== USCoreLaboratoryResultObservationProfile (http://hl7.org/fhir/us/core/StructureDefinition/us-core-observation-lab v7.0.0) =====

/**
 * Branded marker for USCoreLaboratoryResultObservationProfile. Generated by
 * `scripts/codegen-spike.ts` from a cached US Core 7.0 IG. Experimental.
 *
 * Profiled fields walked from `differential`:
 *   - status (min=1 MS binding=required)
 *   - category (min=1 MS slices=[laboratory])
 *   - code (min=1 MS binding=extensible)
 *   - subject (min=1 MS)
 *   - effective[x] (min=1 MS choice=[dateTime|Period])
 *   - value[x] (MS choice=[Quantity|CodeableConcept|string])
 *   - dataAbsentReason (MS)
 *   - referenceRange (MS)
 *
 * Required choice-type constraints:
 *   - effective[x] required (effectiveDateTime | effectivePeriod)
 *
 * Deep must-support paths recorded but not narrowed in the spike:
 *   - Observation.category.coding
 *   - Observation.category.coding.system
 *   - Observation.category.coding.code
 */
declare const USCoreLaboratoryResultObservationProfileBrand: unique symbol;

export type USCoreLaboratoryResultObservationProfileRequired = "status" | "category" | "code" | "subject";

type USCoreLaboratoryResultObservationProfileBase = Omit<Observation, USCoreLaboratoryResultObservationProfileRequired> & {
  readonly [K in USCoreLaboratoryResultObservationProfileRequired]-?: NonNullable<Observation[K]>;
};

export type USCoreLaboratoryResultObservationProfile = USCoreLaboratoryResultObservationProfileBase
  & ({ effectiveDateTime: string } | { effectivePeriod: Period }) & {
  readonly [USCoreLaboratoryResultObservationProfileBrand]: "http://hl7.org/fhir/us/core/StructureDefinition/us-core-observation-lab";
};

/**
 * Brand an unbranded Observation as USCoreLaboratoryResultObservationProfile.
 *
 * The spike does **not** validate at runtime — this is a type-only escape
 * hatch. A real codegen pipeline would either (a) emit a Zod parser per
 * profile, or (b) use `fhirpath` invariants from the SD to drive runtime
 * narrowing.
 */
export function asUSCoreLaboratoryResultObservationProfile(
  resource: USCoreLaboratoryResultObservationProfileBase
  & ({ effectiveDateTime: string } | { effectivePeriod: Period }),
): USCoreLaboratoryResultObservationProfile {
  return resource as USCoreLaboratoryResultObservationProfile;
}

// ===== USCorePatientProfile (http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient v7.0.0) =====

/**
 * Branded marker for USCorePatientProfile. Generated by
 * `scripts/codegen-spike.ts` from a cached US Core 7.0 IG. Experimental.
 *
 * Profiled fields walked from `differential`:
 *   - extension (MS slices=[race,ethnicity,birthsex,genderIdentity])
 *   - identifier (min=1 MS)
 *   - name (min=1 MS)
 *   - telecom (MS)
 *   - gender (min=1 MS binding=required)
 *   - birthDate (MS)
 *   - address (MS)
 *   - communication (MS)
 *
 * Deep must-support paths recorded but not narrowed in the spike:
 *   - Patient.identifier.system
 *   - Patient.identifier.value
 *   - Patient.name.family
 *   - Patient.name.given
 *   - Patient.telecom.system
 *   - Patient.telecom.value
 *   - Patient.address.line
 *   - Patient.address.city
 *   - Patient.address.state
 *   - Patient.address.postalCode
 *   - Patient.communication.language
 */
declare const USCorePatientProfileBrand: unique symbol;

export type USCorePatientProfileRequired = "identifier" | "name" | "gender";

type USCorePatientProfileBase = Omit<Patient, USCorePatientProfileRequired> & {
  readonly [K in USCorePatientProfileRequired]-?: NonNullable<Patient[K]>;
};

export type USCorePatientProfile = USCorePatientProfileBase & {
  readonly [USCorePatientProfileBrand]: "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient";
};

/**
 * Brand an unbranded Patient as USCorePatientProfile.
 *
 * The spike does **not** validate at runtime — this is a type-only escape
 * hatch. A real codegen pipeline would either (a) emit a Zod parser per
 * profile, or (b) use `fhirpath` invariants from the SD to drive runtime
 * narrowing.
 */
export function asUSCorePatientProfile(
  resource: USCorePatientProfileBase,
): USCorePatientProfile {
  return resource as USCorePatientProfile;
}
