import type { ValueSet } from "fhir/r4";

// AUTO-GENERATED by scripts/sync-bundled-valuesets.ts.
// Do not edit by hand.

export const generatedCoreValueSets: Map<string, ValueSet> = new Map(
  [] as [string, ValueSet][],
);
